hl.config({ animations = { enabled = true } })
hl.curve("infinityEase", { type = "bezier", points = { { 0.16, 1 }, { 0.3, 1 } } })
hl.curve("infinityFade", { type = "bezier", points = { { 0.45, 0 }, { 0.2, 1 } } })
hl.curve("infinitySpring", { type = "spring", mass = 1, stiffness = 230, dampening = 25 })
hl.animation({ leaf = "global", enabled = true, speed = 9, bezier = "infinityEase" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.5, spring = "infinitySpring" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4, spring = "infinitySpring", style = "popin 88%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.7, bezier = "infinityFade", style = "popin 88%" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.6, bezier = "infinityEase" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 2.0, bezier = "infinityEase", style = "fade" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "infinityEase" })
