general {
  disable_loading_bar = true
  hide_cursor = true
}

background {
  monitor =
  path = ~/.local/share/infinity-os/current-wallpaper.svg
  blur_passes = 2
  blur_size = 4
}

input-field {
  monitor =
  size = 320, 56
  position = 0, -80
  halign = center
  valign = center
  placeholder_text = Password
  fail_text = Authentication failed
}

label {
  monitor =
  text = Infinity OS
  font_size = 28
  position = 0, 40
  halign = center
  valign = center
}
